### ISSUE TITLE
npm run dev results in module error

### ISSUE THREAD

**Issue by mentix02** [NITKOSG/iknowsomething_backend#32]
$ npm run dev

> social-net@0.0.0 dev /home/<name>/Desktop/oss/iknowsomething_backend
> NODE_ENV='dev' GEN_DOC='false' nodemon --ignore '*.json' app.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/<name>/Desktop/oss/iknowsomething_backend/server.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at loader (/home/<name>/Desktop/oss/iknowsomething_backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/<name>/Desktop/oss/iknowsomething_backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by war-turtle** [comment]
You need to make config.js in the root of the project folder. It isn't shared just because it contains private information.
